# Server
server:
  port: 8090

# Spring
  # Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost/springrestexample
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false